### PR TITLE
Fix issue #24 : The "this" value of decorated methods gets changed

### LINKED ISSUE #24: The "this" value of decorated methods gets changed
I think maybe there is a logic error in the way `@Configurable()` works [here](https://github.com/nestjs-community/nestjs-config/blob/master/src/decorators/Configurable.ts#L20): `apply `changes the value of `this`, so your are not able to call any method or property inside a decorated `method1`:

 ```typescript
@Injectable()
class TestService {
  @Configurable()
  method1(@ConfigParam('foo') foo: string) {
    this.method2();
  }

  method2() {
    console.log('method2');
  }
}
```

> TypeError: this.method2 is not a function

I may be wrong; I'm not a guru in JavaScript but I fear we can't solve this. At least, this should be clearly explained in the documentation.

### PR DESCRIPTION
**Pull request by shekohex**
this will fix #24

### CODE REVIEW

File: src/decorators/Configurable.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export const Configurable = (): MethodDecorator => {
         return p.propertyKey === key;
       });
       return originalMethod.apply(
-        this,
+        target,
```
Comment (shekohex) [inline src/decorators/Configurable.ts]: lol :joy:

**Comment by shekohex** [comment]
I think it's ready to be merged now
cc @bashleigh

**Comment by bashleigh** [comment]
You're free to merge @shekohex :p
